Repository sparta-final-12th-9700/HotDealWave, pull requests merged in 2025-01, with the labels that each got.

#8 User 서비스 Controller, DTO 및 더미데이터 리턴 구현
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/config/SecurityConfig.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/controller/AddressController.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/controller/AuthController.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/controller/UserController.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/ResponseDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/address/request/ReqPatchAddressByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/address/request/ReqPostAddressDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/address/response/ResDeleteAddressByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/address/response/ResGetAddressByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/address/response/ResGetAddressesDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/address/response/ResGetDefaultAddressDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/address/response/ResPatchAddressByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/address/response/ResPatchDefaultAddressByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/address/response/ResPostAddressDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/auth/request/ReqPostCheckEmailDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/auth/request/ReqPostConfirmEmailDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/auth/request/ReqPostLoginDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/auth/request/ReqPostRefreshDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/auth/request/ReqPostSignUpDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/auth/request/ReqPostVerifyEmailDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/auth/response/ResPostLoginDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/auth/response/ResPostRefreshDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/auth/response/ResPostSignUpDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/users/request/ReqPatchUsersInfoByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/users/request/ReqPatchUsersPasswordByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/users/response/ResDeleteUsersByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/users/response/ResGetUsersByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/users/response/ResPatchUsersInfoByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/dtos/users/response/ResPatchUsersPasswordByIdDto.java
  user/src/main/resources/application-local.yml
  user/src/main/resources/application.properties
  user/src/main/resources/application.yml
Labels: ✨ feature

#10 Coupon 서비스 Controller. Dtop, Entity 및 더미데이터 리턴 구현
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/ResponseDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPatchCouponInfosByIdStatusDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPostCouponInfosDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPostCouponValidateDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPostCouponsIssueDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPutCouponInfosByIdDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/PageInfoDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResGetCouponInfosByIdDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResGetCouponInfosDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResGetDailyCouponStatisticsDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResGetUserCouponsDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResPostCouponInfosDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResPostCouponValidateDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/Coupon.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponInfo.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponStatus.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponType.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponController.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponInfoController.java
  coupon/src/main/resources/application.properties
  coupon/src/main/resources/application.yml
Labels: ✨ feature

#12 Company 서비스 Controller, DTO 생성 및 더미데이터 리턴 구현
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/ReqPatchCompanyByIdDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/ReqPatchCompanyByIdStatusDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/ReqPostCompanyDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/ResGetCompanyByIdDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/ResponseDto.java
  company/src/main/java/com/sparta/hotdeal/company/domain/entity/CompanyStatusEnum.java
  company/src/main/java/com/sparta/hotdeal/company/presentation/controller/CompanyController.java
  company/src/main/resources/application.properties
  company/src/main/resources/application.yml
Labels: ✨ feature

#14 Order, Payment Controller 구현 및 더미 Dto 반환
  order/src/main/java/com/sparta/hotdeal/order/OrderApplication.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/BasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/OrderService.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/AuditingDate.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/basket/Basket.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/Order.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/OrderStatus.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/AuditConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/SecurityConfig.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/BasketController.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/ResponseDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/req/ReqPatchBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/req/ReqPostBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/res/ResDeleteBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/res/ResGetBasketByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/res/ResGetBasketsDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/res/ResPatchBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/res/ResPostBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/order/req/ReqPatchOrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/order/req/ReqPostOrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/order/res/ResGetOrderByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/order/res/ResGetOrdersDto.java
  order/src/main/resources/application.properties
  order/src/main/resources/application.yml
  payment/src/main/java/com/sparta/hotdeal/payment/PaymentApplication.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/service/PaymentService.java
  payment/src/main/java/com/sparta/hotdeal/payment/domain/entity/AuditingDate.java
  payment/src/main/java/com/sparta/hotdeal/payment/domain/entity/payment/Payment.java
  payment/src/main/java/com/sparta/hotdeal/payment/domain/entity/payment/PaymentStatus.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/config/AuditConfig.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/config/SecurityConfig.java
  payment/src/main/java/com/sparta/hotdeal/payment/presentation/controller/PaymentController.java
  payment/src/main/java/com/sparta/hotdeal/payment/presentation/dtos/ResponseDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/presentation/dtos/payment/req/ReqPostPaymentConfirmDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/presentation/dtos/payment/req/ReqPostPaymentDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/presentation/dtos/payment/res/ResGetPaymentByIdDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/presentation/dtos/payment/res/ResGetPaymentsDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/presentation/dtos/payment/res/ResPostPaymentConfirmDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/presentation/dtos/payment/res/ResPostPaymentsDto.java
  payment/src/main/resources/application.properties
  payment/src/main/resources/application.yml
Labels: ✨ feature

#13 Review 서비스 Controller, DTO 생성 및 더미데이터 리턴 구현
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/ResponseDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/product/ResGetProductDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/product/ResGetPromotionDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/product/ResProductIdDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/product/ResPromotionIdDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/review/ResGetReviewByIdDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/ProductService.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/AuditingDate.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/File.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/Product.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/ProductCategoryEnum.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/ProductStatusEnum.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/Promotion.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/SubFile.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/AuditConfig.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/SecurityConfig.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ProductController.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/PromotionController.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ReviewController.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/product/ReqPatchUpdateProductStatusDto.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/product/ReqPostCreateProductDto.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/product/ReqPostCreatePromotionDto.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/product/ReqPutUpdateProductDto.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/product/ReqPutUpdatePromotionDto.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/review/ReqPostReviewDto.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/review/ReqPutReviewDto.java
  product/src/main/resources/application.properties
  product/src/main/resources/application.yml
Labels: ✨ feature

#28 업체 CRUD, 유효성 검사, 예외 처리, Auditing 구현
  company/build.gradle
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/ErrorResponseDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/ReqPatchCompanyByIdStatusDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/ResGetCompanyByIdDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/company/ReqPatchCompanyByIdDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/company/ReqPatchCompanyByIdStatusDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/company/ReqPostCompanyDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/company/ResGetCompanyByIdDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/exception/ApplicationException.java
  company/src/main/java/com/sparta/hotdeal/company/application/exception/ErrorCode.java
  company/src/main/java/com/sparta/hotdeal/company/application/exception/GlobalExceptionHandler.java
  company/src/main/java/com/sparta/hotdeal/company/application/service/CompanyService.java
  company/src/main/java/com/sparta/hotdeal/company/domain/AuditingDate.java
  company/src/main/java/com/sparta/hotdeal/company/domain/entity/CompanyStatusEnum.java
  company/src/main/java/com/sparta/hotdeal/company/domain/entity/company/Company.java
  company/src/main/java/com/sparta/hotdeal/company/domain/entity/company/CompanyStatusEnum.java
  company/src/main/java/com/sparta/hotdeal/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/config/AuditConfig.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/config/SecurityConfig.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/exception/CustomAccessDeniedHandler.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/repository/CompanyRepositoryImpl.java
  company/src/main/java/com/sparta/hotdeal/company/presentation/controller/CompanyController.java
  company/src/main/resources/application.yml
Labels: ✨ feature

#22 장바구니 CRUD, Validation, 예외 처리, Security 구현 및 Swagger 연동
  order/build.gradle
  order/src/main/java/com/sparta/hotdeal/order/OrderApplication.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/ErrorResponseDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/ResponseDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/req/ReqPatchBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/req/ReqPostBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/res/ResDeleteBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/res/ResGetBasketByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/res/ResGetBasketListDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/res/ResPatchBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/res/ResPostBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/req/ReqPatchOrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/req/ReqPostOrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResGetOrderByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResGetOrdersDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/ProductDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/ProductListDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/BasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/client/ProductClientService.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/basket/Basket.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/BasketRepository.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/ProductClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/AuditConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/SecurityConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/SwaggerConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/custom/RequestUserDetails.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/custom/SecurityAuditorAware.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/ResGetProductByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/ResGetProductListDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/exception/ApplicationException.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/exception/ErrorCode.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/exception/handler/CustomAccessDeniedHandler.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/exception/handler/GlobalExceptionHandler.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/filter/AuthenticationFilter.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/BasketRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/BasketController.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/req/ReqPatchBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/req/ReqPostBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/res/ResDeleteBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/res/ResGetBasketByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/dtos/basket/res/ResGetBasketsDto.java
  order/src/main/resources/application.yml
Labels: ✨ feature

#30 User 조회, 수정, 삭제 구현
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/ResponseMessage.java
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/users/request/ReqPatchUsersPasswordByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/users/response/ResGetUsersByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/application/exception/ErrorMessage.java
  user/src/main/java/com/sparta/hotdeal/user/application/service/UserService.java
  user/src/main/java/com/sparta/hotdeal/user/domain/entity/User.java
  user/src/main/java/com/sparta/hotdeal/user/domain/repository/UserRepository.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/controller/UserController.java
Labels: ✨ feature

#33 Order 생성
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/ErrorResponseDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/address/res/ResGetAddressByIdForOrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/res/ResGetBasketByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/res/ResGetBasketListDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/coupon/res/ResGetCouponForOrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/req/ReqPostOrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/OrderResponseMessage.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/req/ReqProductReduceQuantityDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/res/ResGetProductByIdForBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/res/ResGetProductListForBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/res/ResGetProductListForOrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/exception/ApplicationException.java
  order/src/main/java/com/sparta/hotdeal/order/application/exception/ErrorCode.java
  order/src/main/java/com/sparta/hotdeal/order/application/exception/GlobalExceptionHandler.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/BasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/OrderService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/client/AddressClientService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/client/CouponClientService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/client/ProductClientService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderBasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderCouponService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderProductService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/AuditingDate.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/Order.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/OrderProduct.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/OrderStatus.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/BasketRepository.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/OrderProductRepository.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/OrderRepository.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/AddressClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/CouponClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/ProductClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/address/ResGetAddressByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/ResGetProductByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/ResGetProductListDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/exception/ErrorCode.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/BasketRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/OrderProductRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/OrderRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java
Labels: ✨ feature

#34 Gateway JWT 토큰 파싱 및 헤더 추가 필터 구현
  gateway/build.gradle
  gateway/src/main/java/com/sparta/hotdeal/gateway/filter/AuthenticationFilter.java
  gateway/src/main/java/com/sparta/hotdeal/gateway/security/JwtUtil.java
  gateway/src/main/resources/application.yml
  user/src/main/java/com/sparta/hotdeal/user/application/service/AuthService.java
  user/src/main/java/com/sparta/hotdeal/user/application/util/JwtUtil.java
Labels: ✨ feature

#27 쿠폰 정보 CRUD, 선착순 쿠폰 발급 구현, 예외 처리, security 구현
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/ErrorResponseDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPatchCouponInfosByIdStatusDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPostCouponInfosDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPutCouponInfosByIdDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/CustomException.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/ErrorCode.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/GlobalExceptionHandler.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/mapper/CouponInfoMapper.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponInfoService.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponService.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponInfo.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/repository/CouponInfoRepository.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/repository/CouponRepository.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/AuditConfig.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/SecurityConfig.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/custom/RequestUserDetails.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/custom/SecurityAuditorAware.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/ApplicationErrorCode.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/ApplicationException.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/handler/CustomAccessDeniedHandler.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/handler/GlobalExceptionHandler.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/filter/AuthenticationFilter.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponController.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponInfoController.java
Labels: ✨ feature

#37 Promotion CRUD 구현
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/product/ReqPostPromotionDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/promotion/ReqPostPromotionDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/promotion/ReqPutPromotionDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/res/promotion/ResGetPromotionDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/res/promotion/ResPostPromotionDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/res/promotion/ResPutPromotionDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/exception/ErrorCode.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/ProductService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/PromotionService.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/Product.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/Promotion.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/promotion/Promotion.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/promotion/PromotionStatusEnum.java
  product/src/main/java/com/sparta/hotdeal/product/domain/repository/product/ProductRepository.java
  product/src/main/java/com/sparta/hotdeal/product/domain/repository/product/PromotionRepository.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryCustom.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryCustomImpl.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/promotion/PromotionRepositoryCustom.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/promotion/PromotionRepositoryCustomImpl.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/promotion/PromotionRepositoryImpl.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/promotion/PromotionRepositoryJpa.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/PromotionController.java
Labels: ✨ feature

#39 주문 내역 조회 및 상세 조회, Adapter, Port 도입
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/address/AddressDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/res/ResGetBasketByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/basket/res/ResGetBasketListDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/coupon/CouponDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResGetOrderByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResGetOrderListDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResGetOrdersDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order_product/OrderProductDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/ProductByIdtDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/ProductDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/res/ResGetProductByIdForBasketDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/user/UserDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/port/CouponClientPort.java
  order/src/main/java/com/sparta/hotdeal/order/application/port/ProductClientPort.java
  order/src/main/java/com/sparta/hotdeal/order/application/port/UserClientPort.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/BasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/client/AddressClientService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/client/CouponClientService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/client/ProductClientService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderBasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderCouponService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderDetailService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderProductService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/AuditingDate.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/Order.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/OrderProductRepository.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/OrderRepository.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/CouponClientAdapter.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/ProductClientAdapter.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/UserClientAdapter.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/CouponClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/ProductClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/UserClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/address/ResGetAddressByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/ResGetProductByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/ResGetProductListDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/user/ResGetUserByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/OrderProductRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/OrderRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java
Labels: ✨ feature, ♻️ refactor

#42 Address CRUD 및 Security 구현
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/ResponseMessage.java
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/address/request/ReqPostAddressDto.java
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/address/response/ResGetAddressByIdDto.java
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/address/response/ResGetAddressesDto.java
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/address/response/ResGetDefaultAddressDto.java
  user/src/main/java/com/sparta/hotdeal/user/application/exception/ErrorMessage.java
  user/src/main/java/com/sparta/hotdeal/user/application/service/AddressService.java
  user/src/main/java/com/sparta/hotdeal/user/domain/entity/Address.java
  user/src/main/java/com/sparta/hotdeal/user/domain/entity/User.java
  user/src/main/java/com/sparta/hotdeal/user/domain/repository/AddressRepository.java
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/config/SecurityConfig.java
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/filter/AuthenticationFilter.java
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/repository/AddressRepositoryImpl.java
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/security/RequestUserDetails.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/controller/AddressController.java
Labels: ✨ feature

#47 Review CRUD 구현
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/review/ReqPostReviewDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/review/ReqPutReviewDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/res/review/ResGetReviewByIdDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/ReviewService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/client/OrderClientService.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/File.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/review/Review.java
  product/src/main/java/com/sparta/hotdeal/product/domain/repository/review/ReviewRepository.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/client/OrderClient.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/dtos/ResGetOrderByIdDto.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/review/ReviewRepositoryImpl.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ReviewController.java
Labels: ✨ feature

#48 User 서비스 리팩토링(Audit, UserDetails 등)
  user/build.gradle
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/auth/request/ReqPostCheckEmailDto.java
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/auth/request/ReqPostConfirmEmailDto.java
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/auth/request/ReqPostSignUpDto.java
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/auth/request/ReqPostVerifyEmailDto.java
  user/src/main/java/com/sparta/hotdeal/user/application/exception/GlobalExceptionHandler.java
  user/src/main/java/com/sparta/hotdeal/user/application/service/AuthService.java
  user/src/main/java/com/sparta/hotdeal/user/application/service/UserService.java
  user/src/main/java/com/sparta/hotdeal/user/domain/entity/Audit.java
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/filter/AuthenticationFilter.java
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/security/SecurityAuditorAware.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/controller/AuthController.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/controller/UserController.java
  user/src/main/resources/application.yml
Labels: ♻️ refactor

#43 Order security 필터 세부 구현
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/ProductClientAdapter.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/SecurityConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/custom/RequestUserDetails.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/custom/SecurityAuditorAware.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/ResGetProductByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/ResGetProductListDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/exception/handler/CustomAuthenticationHandler.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/filter/AuthenticationFilter.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/BasketController.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java
Labels: ✨ feature

#46 Coupon 사용관련 로직, 사용자의 쿠폰 조회, 삭제, 스케쥴러 기능 구현
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/ErrorResponseDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResPostCouponValidateDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/ErrorCode.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/GlobalExceptionHandler.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/mapper/CouponMapper.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/scheduler/CouponExpirationScheduler.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponInfoService.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponService.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/SchedulerService.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/AuditingDate.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/Coupon.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponInfo.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/repository/CouponInfoRepository.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/repository/CouponRepository.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/SecurityConfig.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/custom/RequestUserDetails.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/custom/SecurityAuditorAware.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/ApplicationErrorCode.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/ApplicationException.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/handler/CustomAuthenticationHandler.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/handler/GlobalExceptionHandler.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/filter/AuthenticationFilter.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/repository/CouponInfoRepositoryImpl.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/repository/CouponRepositoryImpl.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponController.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponInfoController.java
Labels: ✨ feature, ♻️ refactor

#53 Product 수량 감소, 수량 복구 하는 로직 수정 및 Security 필터 구현
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/product/ReqPatchProductQuantityDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/promotion/ReqPromotionQuantityDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/exception/ErrorCode.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/ProductPromotionHelperService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/ProductService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/PromotionService.java
  product/src/main/java/com/sparta/hotdeal/product/domain/repository/product/ProductRepository.java
  product/src/main/java/com/sparta/hotdeal/product/domain/repository/product/PromotionRepository.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/AuditConfig.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/SecurityConfig.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/custom/RequestUserDetails.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/custom/SecurityAuditorAware.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/exception/handler/CustomAuthenticationHandler.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/filter/AuthenticationFilter.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryCustom.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryImpl.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryJpa.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/promotion/PromotionRepositoryImpl.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/promotion/PromotionRepositoryJpa.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ProductController.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/PromotionController.java
  product/src/main/resources/application.yml
Labels: ♻️ refactor

#55 Company 유효성 메세지 추가, Security 필터, 권한 구현
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/company/ReqPatchCompanyByIdDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/company/ReqPatchCompanyByIdStatusDto.java
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/company/ReqPostCompanyDto.java
  company/src/main/java/com/sparta/hotdeal/company/domain/entity/Audit.java
  company/src/main/java/com/sparta/hotdeal/company/domain/entity/company/Company.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/config/SecurityConfig.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/exception/CustomAuthenticationHandler.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/filter/AuthenticationFilter.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/security/RequestUserDetails.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/security/SecurityAuditorAware.java
  company/src/main/java/com/sparta/hotdeal/company/presentation/controller/CompanyController.java
Labels: ♻️ refactor

#69 User, Gateway, Eureka Server Dockerfile 및 docker-compose.yml 파일 수정
  docker-compose.yml
  gateway/Dockerfile
  server/Dockerfile
  user/Dockerfile
Labels: 🧹 chore

#73 User 서비스 Swagger 적용
  user/build.gradle
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/config/SwaggerConfig.java
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/filter/AuthenticationFilter.java
  user/src/main/resources/application-local.yml
Labels: ✨ feature, ♻️ refactor

#76 Gateway filter Swagger 경로 추가
  gateway/build.gradle
  gateway/src/main/java/com/sparta/hotdeal/gateway/filter/AuthenticationFilter.java
  gateway/src/main/resources/application-local.yml
  gateway/src/main/resources/application-prod.yml
  gateway/src/main/resources/application.yml
Labels: ♻️ refactor

#70 Product 서비스 Swagger 적용 및 리팩토링
  product/build.gradle
  product/src/main/java/com/sparta/hotdeal/product/ProductApplication.java
  product/src/main/java/com/sparta/hotdeal/product/application/exception/ErrorCode.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/ReviewService.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/client/CompanyClient.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/CompanyClientConfig.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/SwaggerConfig.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/exception/decoder/CompanyClientErrorDecoder.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/filter/AuthenticationFilter.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ProductController.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/PromotionController.java
  product/src/main/resources/application.yml
Labels: 📝 docs, ♻️ refactor

#74 Order Feign Client 연결 및 오류 수정, 테스트
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/ErrorResponseDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/coupon/CouponValidationDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/OrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResGetOrderByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResGetOrderListDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResPostOrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order_product/OrderProductDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/payment/PaymentRequestDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/req/ReqProductReduceQuantityDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/port/CouponClientPort.java
  order/src/main/java/com/sparta/hotdeal/order/application/port/PaymentClientPort.java
  order/src/main/java/com/sparta/hotdeal/order/application/port/ProductClientPort.java
  order/src/main/java/com/sparta/hotdeal/order/application/port/UserClientPort.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/BasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderBasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderDetailService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderProductService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java
  order/src/main/java/com/sparta/hotdeal/order/common/exception/ApplicationException.java
  order/src/main/java/com/sparta/hotdeal/order/common/exception/ErrorCode.java
  order/src/main/java/com/sparta/hotdeal/order/common/exception/GlobalExceptionHandler.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/Order.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/OrderProduct.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/OrderProductRepository.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/CouponClientAdapter.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/PaymentClientAdapter.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/ProductClientAdapter.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/UserClientAdapter.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/CouponClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/PaymentClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/ProductClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/UserClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/CouponClientConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/PaymentClientConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/ProductClientConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/UserClientConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/ResponseDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/coupon/req/ReqPostCouponValidateDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/coupon/res/ResPostCouponValidateDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/payment/req/ReqPostPaymentDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/payment/res/ResPostPaymentsDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/req/ReqPatchProductQuantityDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/res/ResGetProductByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/res/ResGetProductListDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/product/res/ResPatchReduceProductQuantityDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/exception/decoder/CouponClientErrorDecoder.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/exception/decoder/PaymentClientErrorDecoder.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/exception/decoder/ProductClientErrorDecoder.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/exception/decoder/UserClientErrorDecoder.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/OrderProductRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/OrderRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java
  order/src/main/resources/application.yml
Labels: ♻️ refactor

#78 Gateway에 필터를 수행하지 않을 경로 추가(payment, product, review)
  gateway/src/main/java/com/sparta/hotdeal/gateway/filter/AuthenticationFilter.java
  gateway/src/main/resources/application.yml
Labels: ♻️ refactor

#80 swagger 설정 추가 및 쿠폰info 생성, 유효성 검사 리팩토링
  coupon/build.gradle
  coupon/src/main/java/com/sparta/hotdeal/coupon/CouponApplication.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPostCouponValidateDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/ErrorCode.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponInfoService.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponService.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/client/CompanyClientService.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/client/CompanyClient.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/CompanyClientConfig.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/SwaggerConfig.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/dto/ResGetCompanyByIdDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/decoder/CompanyClientErrorDecoder.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponController.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponInfoController.java
Labels: ♻️ refactor, 🧹 chore

#66 Company 도메인 Swagger 적용 및 필터 수정
  company/build.gradle
  company/src/main/java/com/sparta/hotdeal/company/application/dtos/ErrorResponseDto.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/config/SwaggerConfig.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/filter/AuthenticationFilter.java
  company/src/main/java/com/sparta/hotdeal/company/presentation/controller/CompanyController.java
  company/src/main/resources/application.yml
Labels: ♻️ refactor

#81 Review 도메인 타입 수정 및 리팩토링
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/review/ReqPostReviewDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/res/review/ResGetReviewByIdDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/ReviewService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/client/UserClientService.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/review/Review.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/client/UserClient.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/dtos/ResGetUserByIdDto.java
Labels: ♻️ refactor

#82 couponInfos URI 를 coupon-infos 로 누락된 부분도 수정
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponInfoService.java
Labels: 🐛 fix

#83 쿠폰 info 생성 시 company null 분기처리
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponInfoService.java
  coupon/src/main/resources/application.yml
Labels: 🐛 fix

#84 Product 서비스 AuthenticationFilter 수정
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/filter/AuthenticationFilter.java
Labels: ♻️ refactor

#89 Review 도메인 User feign client 적용 및 로그 추가
  product/src/main/java/com/sparta/hotdeal/product/application/exception/ErrorCode.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/ReviewService.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/client/OrderClient.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/client/UserClient.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/OrderClientConfig.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/UserClientConfig.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/exception/decoder/OrderClientErrorDecoder.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/exception/decoder/UserClientErrorDecoder.java
Labels: ✨ feature

#86 Order feignClient 리팩토링 및 Swagger 추가
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderBasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/BasketRepository.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/CouponClientAdapter.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/ProductClient.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/SwaggerConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/coupon/req/ReqPostCouponValidateDto.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/filter/AuthenticationFilter.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/BasketController.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java
  order/src/main/resources/application.yml
Labels: 📝 docs, ♻️ refactor

#95 payment application.yml 스키마 이름 오타 수정
  payment/src/main/resources/application-local.yml
  payment/src/main/resources/application-prod.yml
Labels: 🧹 chore

#96 docker-compose의 gateway 환경변수 누락 수정 (#93)
  docker-compose.yml
Labels: 🧹 chore

#100 Product 도메인 내 ratingSum, reviewCnt 초기값 추가
  product/src/main/java/com/sparta/hotdeal/product/application/service/ProductService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/ReviewService.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/Product.java
Labels: ♻️ refactor

#102 Order 결제 요청 오류 수정
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java
Labels: 🐛 fix

#106 User 서비스 로그 모니터링 시스템 구축 테스트
  monitoring/loki/loki-config.yml
  user/build.gradle
  user/src/main/java/com/sparta/hotdeal/user/application/exception/GlobalExceptionHandler.java
  user/src/main/resources/logback.xml
Labels: ✨ feature, 🧹 chore

#108 토큰 재발급 기능 구현
  user/src/main/java/com/sparta/hotdeal/user/application/dtos/ResponseMessage.java
  user/src/main/java/com/sparta/hotdeal/user/application/exception/CustomJwtExcpetion.java
  user/src/main/java/com/sparta/hotdeal/user/application/exception/ErrorMessage.java
  user/src/main/java/com/sparta/hotdeal/user/application/exception/GlobalExceptionHandler.java
  user/src/main/java/com/sparta/hotdeal/user/application/exception/JwtExceptionMessage.java
  user/src/main/java/com/sparta/hotdeal/user/application/service/AuthService.java
  user/src/main/java/com/sparta/hotdeal/user/application/util/JwtUtil.java
  user/src/main/java/com/sparta/hotdeal/user/presentation/controller/AuthController.java
  user/src/main/resources/application.yml
Labels: ✨ feature, ♻️ refactor

#109 Order Payment 주문 취소, 주문 환불, 결제 취소 구현
  order/src/main/java/com/sparta/hotdeal/order/application/service/BasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderBasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java
  order/src/main/java/com/sparta/hotdeal/order/common/exception/ErrorCode.java
  order/src/main/java/com/sparta/hotdeal/order/common/exception/GlobalExceptionHandler.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/AuditingDate.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/basket/Basket.java
  order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/OrderStatus.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/BasketRepository.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/OrderProductRepository.java
  order/src/main/java/com/sparta/hotdeal/order/domain/repository/OrderRepository.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/BasketRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/OrderProductRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/OrderRepositoryImpl.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/jpa/BasketRepositoryJpa.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/jpa/OrderProductRepositoryJpa.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/repository/jpa/OrderRepositoryJpa.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/BasketController.java
  order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/dtos/kakaopay/KakaoPayCancelDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/dtos/payment/PaymentDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/dtos/payment/res/ResPostPaymentCancelDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/exception/GlobalExceptionHandler.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/port/KakaoPayClientPort.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/service/PaymentService.java
  payment/src/main/java/com/sparta/hotdeal/payment/domain/entity/payment/Payment.java
  payment/src/main/java/com/sparta/hotdeal/payment/domain/entity/payment/PaymentStatus.java
  payment/src/main/java/com/sparta/hotdeal/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/adapter/KakaoPayClientAdapter.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/client/KakaoPayClient.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/dto/kakaopay/req/ReqDeleteKakaoPayCancelDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/dto/kakaopay/res/ResDeleteKakaoPayCancelDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/mapper/KakaoPayMapper.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/repository/jpa/PaymentRepositoryJpa.java
  payment/src/main/java/com/sparta/hotdeal/payment/presentation/controller/PaymentController.java
Labels: ✨ feature

#114 이메일 인증 비동기 처리 구현
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/config/AsyncConfig.java
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/service/MailServiceImpl.java
Labels: ♻️ refactor

#118 선착순 쿠폰 발급 성능 테스트 및 개선
  coupon/build.gradle
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/ErrorCode.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/GlobalExceptionHandler.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponIssueHelper.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponService.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponInfo.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/RedissonConfig.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/filter/AuthenticationFilter.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponController.java
  coupon/src/main/resources/application-local.yml
  coupon/src/main/resources/application-prod.yml
Labels: ♻️ refactor, ✅ test

#119 Product 상품 재고 차감 및 복구에 대한 Kafka 구현
  product/build.gradle
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/product/ReqPatchProductQuantityDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/product/ReqPutProductQuantityDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/res/product/ResPatchReduceProductQuantityDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/dtos/res/product/ResPutProductQuantityDto.java
  product/src/main/java/com/sparta/hotdeal/product/application/exception/ErrorCode.java
  product/src/main/java/com/sparta/hotdeal/product/application/scheduler/PromotionScheduler.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/ProductPromotionHelperService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/file/FileService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/file/SubFileService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/product/ProductInventoryService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/product/ProductService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/promotion/PromotionSchedulerService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/promotion/PromotionService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/review/ReviewService.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/Product.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/promotion/Promotion.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/client/CompanyClient.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/ConsumerApplicationKafkaConfig.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/ProducerApplicationKafkaConfig.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/kafka/ProductKafkaConsumer.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/kafka/ProductKafkaProducer.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ProductController.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/PromotionController.java
  product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ReviewController.java
  product/src/main/resources/application-local.yml
Labels: 🐛 fix, ♻️ refactor, 🧹 chore

#116 Company 목록 조회 시 쿼리파라미터 및 인덱싱 추가
  company/src/main/java/com/sparta/hotdeal/company/application/service/CompanyService.java
  company/src/main/java/com/sparta/hotdeal/company/domain/entity/company/Company.java
  company/src/main/java/com/sparta/hotdeal/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/sparta/hotdeal/company/presentation/controller/CompanyController.java
Labels: ♻️ refactor

#134 Product 목록 조회 고도화 및 테스트 코드 작성
  product/build.gradle
  product/src/main/java/com/sparta/hotdeal/product/application/service/product/ProductIndexService.java
  product/src/main/java/com/sparta/hotdeal/product/application/service/product/ProductService.java
  product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/ProductDocument.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/ElasticsearchConfig.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/kafka/ProductKafkaConsumer.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductSearchRepository.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductSearchRepositoryCustom.java
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductSearchRepositoryCustomImpl.java
  product/src/main/resources/application-local.yml
  product/src/main/resources/application-prod.yml
  product/src/main/resources/application.yml
  product/src/test/java/com/sparta/hotdeal/product/ProductControllerTest.java
  product/src/test/java/com/sparta/hotdeal/product/PromotionControllerTest.java
Labels: ♻️ refactor, ✅ test, 🧹 chore

#135 Gateway 필터를 수행하지 않을 경로를 Enum으로 관리하도록 변경
  gateway/src/main/java/com/sparta/hotdeal/gateway/filter/AllowedPath.java
  gateway/src/main/java/com/sparta/hotdeal/gateway/filter/AuthenticationFilter.java
Labels: ♻️ refactor

#126 Order 주문 생성 카프카 적용
  order/build.gradle
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResGetOrderByIdDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResPostOrderDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/payment/req/ReqReadyPaymentDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/dtos/product/req/ReqProductReduceQuantityDto.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/BasketService.java
  order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java
  order/src/main/java/com/sparta/hotdeal/order/common/exception/GlobalExceptionHandler.java
  order/src/main/java/com/sparta/hotdeal/order/event/consumer/OrderEventConsumer.java
  order/src/main/java/com/sparta/hotdeal/order/event/message/ReqOrderCancelMessage.java
  order/src/main/java/com/sparta/hotdeal/order/event/producer/OrderEventProducer.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/ConsumerApplicationKafkaConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/ProducerApplicationKafkaConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/custom/SecurityAuditorAware.java
  order/src/main/resources/application-local.yml
  order/src/main/resources/application-prod.yml
  order/src/main/resources/application.yml
  payment/build.gradle
  payment/src/main/java/com/sparta/hotdeal/payment/application/dtos/order/OrderDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/dtos/payment/res/ResGetPaymentByIdDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/port/KakaoPayClientPort.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/port/OrderClientPort.java
  payment/src/main/java/com/sparta/hotdeal/payment/application/service/PaymentService.java
  payment/src/main/java/com/sparta/hotdeal/payment/domain/entity/payment/Payment.java
  payment/src/main/java/com/sparta/hotdeal/payment/event/consumer/PaymentDlqConsumer.java
  payment/src/main/java/com/sparta/hotdeal/payment/event/consumer/PaymentEventConsumer.java
  payment/src/main/java/com/sparta/hotdeal/payment/event/message/ReqProductRecoverQuantityDto.java
  payment/src/main/java/com/sparta/hotdeal/payment/event/message/ReqReadyPaymentMessage.java
  payment/src/main/java/com/sparta/hotdeal/payment/event/producer/PaymentEventProducer.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/adapter/KakaoPayClientAdapter.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/adapter/OrderClientAdapter.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/client/OrderClient.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/config/ConsumerApplicationKafkaConfig.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/config/ProducerApplicationKafkaConfig.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/custom/SecurityAuditorAware.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/dto/order/res/ResGetOrderByIdDto.java
  payment/src/main/resources/application-local.yml
  payment/src/main/resources/application-prod.yml
  payment/src/main/resources/application.yml
Labels: ♻️ refactor

#132 User 서비스 일부 클래스 패키지 변경
  user/src/main/java/com/sparta/hotdeal/user/application/service/AuthService.java
  user/src/main/java/com/sparta/hotdeal/user/libs/config/AsyncConfig.java
  user/src/main/java/com/sparta/hotdeal/user/libs/util/JwtUtil.java
Labels: 🧹 chore

#138 docker-compose.yml 수정
  docker-compose.yml
Labels: 🧹 chore

#125 쿠폰 정보 목록 조회/서치 기능 구현, 쿠폰과 쿠폰정보 컨트롤러 테스트 작성
  coupon/build.gradle
  coupon/src/main/java/com/sparta/hotdeal/coupon/CouponApplication.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResGetCouponInfosDto.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/ErrorCode.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/mapper/CouponInfoMapper.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponInfoService.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/domain/repository/CouponInfoRepository.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/QuerydslConfig.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/RedissonConfig.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/repository/CouponInfoRepositoryCustom.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/repository/CouponInfoRepositoryCustomImpl.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/repository/CouponInfoRepositoryImpl.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponController.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponInfoController.java
  coupon/src/test/java/com/sparta/hotdeal/coupon/controller/CouponControllerTest.java
  coupon/src/test/java/com/sparta/hotdeal/coupon/controller/CouponInfoControllerTest.java
Labels: ✨ feature, 🐛 fix, ✅ test, 🧹 chore

#137 Prometheus 의존성 추가 및 서비스 메트릭 모니터링 시스템 구축
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/config/SecurityConfig.java
  company/src/main/java/com/sparta/hotdeal/company/infrastructure/filter/AuthenticationFilter.java
  company/src/main/resources/application.yml
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/SecurityConfig.java
  coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/filter/AuthenticationFilter.java
  coupon/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
  monitoring/prometheus/prometheus.yml
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/SecurityConfig.java
  order/src/main/java/com/sparta/hotdeal/order/infrastructure/filter/AuthenticationFilter.java
  order/src/main/resources/application.yml
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/config/SecurityConfig.java
  payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/filter/AuthenticationFilter.java
  payment/src/main/resources/application.yml
  product/src/main/java/com/sparta/hotdeal/product/infrastructure/filter/AuthenticationFilter.java
  product/src/main/resources/application.yml
  user/src/main/java/com/sparta/hotdeal/user/infrastructure/filter/AuthenticationFilter.java
  user/src/main/resources/application.yml
Labels: ✨ feature, 🧹 chore

#141 Order application 파일 consumer, producer kafka endpoint 설정 추가
  order/src/main/resources/application-local.yml
  order/src/main/resources/application-prod.yml
  payment/src/main/resources/application-local.yml
  payment/src/main/resources/application-prod.yml
Labels: 🐛 fix

#143 Company 트랜잭션 누락 추가
  company/src/main/java/com/sparta/hotdeal/company/application/service/CompanyService.java
Labels: 🐛 fix

#144 프로모션 수정 리팩토링 및 카프카 관련 yml 수정
  product/src/main/java/com/sparta/hotdeal/product/application/service/promotion/PromotionService.java
  product/src/main/resources/application-prod.yml
Labels: ♻️ refactor

#145 chore: github actions 워크플로우 파일 작성 (#121)
  .github/workflows/actions.yml
Labels: 🧹 chore

#147 github actions 워크플로우에 빌드 추가 및 docker-compsoe.yml 수정
  .github/workflows/actions.yml
  docker-compose.yml
Labels: 🧹 chore

#151 README 작성
  README.md
Labels: 📝 docs

#152 docs: 리드미 수정
  README.md
Labels: 📝 docs

#153 리드미 누락 변경
  README.md
Labels: 📝 docs
